### ISSUE TITLE
Not Working for iPhone XS Max

### ISSUE THREAD

**Issue by zjfjack** [shinydevelopment/SimulatorStatusMagic#68] opened 2018-09-13 06:16 UTC
Hi,
Thanks for this amazing project.
I've been using your library around 1 year, and it's really helpful for me to create screenshots.

Apple just released the new products, and the most disgusting thing is that the iTunesConnect forces us to upload 6.5 inch screenshots and all previous 5.8 inch screenshots for iPhone X are gone and not supported. I tried your library with iPhone XS Max but it is not working. Hopefully you can fix it soon.

Thanks
Jeff

**Comment by daveverwer** [comment] 2018-09-13 12:10
You should find some progress on this from @cysp today which I just merged into master. Also, please feel free to experiment with this and see if you can push it forward as well.

**Comment by tfonfara** [comment] 2018-09-13 14:37
@zjfjack 6.5" screenshots are optional so far 😉

**Comment by zjfjack** [comment] 2018-09-14 01:08
@tfonfara omg, thanks for letting me know. 

Unfortunately I've already released the version with the wrong pictures for 5.8 inch. I don't know there is a media manager. NVM, I will fix this in next release.

**Comment by zjfjack** [comment] 2018-09-14 01:15
@daveverwer Thanks for the updating.

**Comment by tfonfara** [comment] 2018-09-15 10:01
I can confirm that it is working perfectly for iPhone X Max with latest GM fix 👍
Only thing I noticed, on iPad there's with iOS 12 the date displayed in the status bar, that can't be configured currently, but that's a new feature not a bug.

**Comment by daveverwer** [comment] 2018-09-16 08:35
Yea there are also some other bugs with cellular options on iPad, it needs some work still.

**Comment by rcfrias** [comment] 2018-09-18 21:50
Bluetooth is also not responding to the settings...

**Comment by daveverwer** [comment] 2019-01-06 00:52
I believe this is all working now. Closing.

**Closed by daveverwer** 2019-01-06 00:52 UTC
