### ISSUE TITLE
Custom clock is not horisontally centered

### ISSUE THREAD

**Issue by maxrudberg** [shinydevelopment/SimulatorStatusMagic#29] opened 2015-11-11 14:52 UTC
SF UI font is wider tha Helvetica, so my guess it that its position is being calculated based on the previous font. It's slight off center, to the right.

**Comment by daveverwer** [comment] 2015-11-11 20:15
Could you provide some screenshots of what you're seeing please?

Unfortunately, I'm pretty sure this isn't something we can fix as we don't have any control over the positioning of the time.

**Comment by rbaulin** [comment] 2016-01-19 23:34
My guess is @maxrudberg observes something similar:

![sample](https://cloud.githubusercontent.com/assets/679174/12435329/f7714aa6-bf1d-11e5-8cde-ea2453130ae4.png)

**Comment by daveverwer** [comment] 2016-01-20 11:03
I agree that's off centre, but I still don't think there's anything we can do to fix it since we don't set the position :(

**Comment by daveverwer** [comment] 2016-03-26 10:58
Just checked into this again and I can't reproduce this, it's perfectly centred for me.

![centred](https://cloud.githubusercontent.com/assets/5180/14059681/a76ade48-f341-11e5-928f-aea243191da9.png)

**Comment by sgtsquiggs** [comment] 2016-05-24 15:20
I had this same exact issue. It started happening when Xcode added new simulators. I ran the app above, reset, and reapplied the custom status bar. This fixed the issue for me.

**Closed** 2016-08-29 20:26 UTC
