### ISSUE TITLE
Bug - black box appears in status bar

### ISSUE THREAD

**Issue by rbaulin** [shinydevelopment/SimulatorStatusMagic#20] opened 2015-05-03 16:44 UTC
iPhone 6 simulator, iOS 8.3

Please see the screenshot below:
![ios simulator screen shot 03 may 2015 19 41 31](https://cloud.githubusercontent.com/assets/679174/7445845/9213b942-f1cc-11e4-8369-1e84318ee99f.png)

Thanks for great library!

**Comment by KrauseFx** [comment] 2015-05-03 23:38
Just ran into the same issue.

**Comment by rbaulin** [comment] 2015-05-03 23:58
@KrauseFx I have tried to locate the issue by commenting out different injections and restarting simulator. At some point the black box has just magically disappeared. Cannot reproduce the issue with the original source code now.

**Comment by daveverwer** [comment] 2015-05-04 09:34
Not happening for me with 6.3.1/8.3. Are you on the 6.4/8.4 beta?

**Comment by daveverwer** [comment] 2015-05-04 09:35
Sorry, just re-read the top of the report. You're on 6.3/8.3.

**Comment by martinnormark** [comment] 2015-05-08 22:08
Getting this as well on 6.3.1/8.3 - causing instruments for wait forever...

```shell
Waiting for device to boot...
2015-05-08 22:03:34 +0000 Default: Loading indicator is visible... waiting
2015-05-08 22:03:35 +0000 Default: Loading indicator is visible... waiting
2015-05-08 22:03:36 +0000 Default: Loading indicator is visible... waiting
2015-05-08 22:03:37 +0000 Default: Loading indicator is visible... waiting
2015-05-08 22:03:38 +0000 Default: Loading indicator is visible... waiting
```

**Comment by ZevEisenberg** [comment] 2015-05-12 01:58
+1 am seeing the box as well. Xcode 6.3, iOS 8.3 simulator.

**Comment by NickEntin** [comment] 2015-06-01 00:08
Am seeing the same issue with Xcode 6.3.2, iOS 8.3 simulator

**Comment by sdjm-tessella** [comment] 2015-09-21 10:56
I saw this in all of my iOS 8.4 simulators.  I reset the contents and settings for those simulators and the problem went away.

**Comment by lavoy** [comment] 2015-09-24 15:29
+1 Seeing this too in Xcode 7 on iOS 8.4 and iOS 9 simulators.

**Comment by makadaw** [comment] 2016-02-22 10:28
+1 Xcode 7.2.1 and iOS 3.4 and 9.2 simulators

**Comment by daveverwer** [comment] 2016-02-22 11:13
@lavoy @makadaw Does resetting the simulators as @sdjm-tessella suggested work for you?

Something like https://github.com/fastlane/snapshot#user-content-completely-reset-all-simulators should do the trick in the easiest way.

**Comment by makadaw** [comment] 2016-02-22 11:35
Hi @daveverwer,

Its works (or just reset simulator data), but next time I start snapshot this black box appears

**Comment by ricsantos** [comment] 2016-03-22 02:44
This issue seems to be back in Xcode 7.3 / iOS 9.3 Simulators.

**Comment by davidrothera** [comment] 2016-03-22 13:42
Also seeing this in the 7.3 / 8.3 simulators, tried clearing the content and settings and still seeing the same.

![screen shot 2016-03-22 at 13 42 04](https://cloud.githubusercontent.com/assets/2766321/13953452/ee49e806-f033-11e5-83ed-35998270f7ca.png)

**Comment by daveverwer** [comment] 2016-03-26 10:54
I've still never seen this occur. It's very strange.

Can anyone reproduce this independently of using SimulatorStatusMagic with fastlane snapshot?

**Comment by Hs-Yeah** [comment] 2016-03-28 10:57
I am using Xcode 7.3 and iOS 9.3 Simulator, after `pod install` I built and ran the app in the simulator and the black box appeared.

Then I cloned the repo from github, built and ran the SimulatorStatusMagic app in the simulator and everything was fine.

Compared the installed pod with the source code of the SimulatorStatusMagic app, I found out the iOS 9.3 overrider source file is not populated in the installed pod directory.

Then the investigation revealed that my cocoapods setup was messed up and led to the installation of old 1.7 version of SimulatorStatusMagic.

After a reset of cocoapods I use `pod update` to install the latest 1.8 version of SimulatorStatusMagic and the problem is resolved.

**Comment by plaetzchen** [comment] 2016-04-07 13:40
I fixed it with the following:

- Update SimulatorStatusMagic to 1.8
- run ```snapshot reset_simulators```

And *ta da* the black box is gone.

**Comment by nobre84** [comment] 2016-05-07 19:10
I got this one as well. My Podfile had `platform :ios, '7.0'` and your podspec says 8.0, so `pod install` always grabbed v1.7 instead of v1.8. Updated that an ran `pod update SimulatorStatusMagic`, all good now.

**Comment by fruitcoder** [comment] 2016-05-31 11:12
I got this issue with XCode 7.3 and iOS 9.3 Simulators with the sample project (neither pod or fastlane used)

**Comment by ConfusedVorlon** [comment] 2016-07-27 09:38
I just hit this today with xcode 7.3, ios 9.3 and snapshot.

Using snapshot's 'reset simulators' command didn't help.

**Comment by daveverwer** [comment] 2017-12-26 11:32
Closing this as it's not been seen in 18 months 😄

**Closed by daveverwer** 2017-12-26 11:32 UTC
